apiVersion: v1
kind: Pod
metadata:
  name: pod-single
  labels:
    app.kubernetes.io/name: pod-single
    app.kubernetes.io/part-of: cka-lab
    app.kubernetes.io/managed-by: manual
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    ports:
    - containerPort: 80
