apiVersion: v1
kind: Pod
metadata:
  name: pod-broken
  labels:
    app.kubernetes.io/name: pod-broken
    app.kubernetes.io/part-of: cka-lab
    app.kubernetes.io/managed-by: manual
spec:
  containers:
  - name: app
    image: nginxs:1.25
    ports:
    - containerPort: 80
